version: 0.0
os: linux
files:
  - source: public
    destination: /var/www/html/public
  - source: src
    destination: /var/www/html/src
  - source: /package-lock.json
    destination: /var/www/html/
  - source: /package.json
    destination: /var/www/html/
  - source: public/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
